# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-09 14:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delibere', '0002_auto_20170509_1635'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delibera',
            old_name='note',
            new_name='notes',
        ),
    ]
