# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-09 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delibere', '0004_auto_20170509_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='delibera',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='delibera',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
