# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-09 14:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delibere', '0005_auto_20170509_1646'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delibera',
            old_name='create_date',
            new_name='creates_at',
        ),
        migrations.RenameField(
            model_name='delibera',
            old_name='modified_date',
            new_name='modified_at',
        ),
    ]
