# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-09 14:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delibere', '0006_auto_20170509_1648'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delibera',
            old_name='creates_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='delibera',
            old_name='modified_at',
            new_name='updated_at',
        ),
    ]
