# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-09 17:05
from __future__ import unicode_literals

import delibere.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delibere', '0007_auto_20170509_1650'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filepath', models.CharField(max_length=256, null=True)),
                ('file', models.FileField(blank=True, max_length=255, null=True, upload_to=delibere.models.upload_to)),
                ('nome', models.CharField(max_length=32, null=True)),
                ('tipo_documento', models.CharField(help_text='P - Principale, A - Allegato', max_length=1)),
            ],
            options={
                'verbose_name': 'documento',
                'verbose_name_plural': 'documenti',
            },
        ),
        migrations.AlterField(
            model_name='delibera',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='documento',
            name='delibera',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='delibere.Delibera'),
        ),
    ]
