# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-09 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delibere', '0008_auto_20170509_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='estensione',
            field=models.CharField(default='', help_text="L'estensione del documento", max_length=4),
            preserve_default=False,
        ),
    ]
