# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-09 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delibere', '0009_documento_estensione'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amministrazione',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice', models.CharField(blank=True, max_length=5, null=True)),
                ('denominazione', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name_plural': 'amministrazioni',
            },
        ),
    ]
