# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-09 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delibere', '0010_amministrazione'),
    ]

    operations = [
        migrations.AddField(
            model_name='delibera',
            name='amministrazioni',
            field=models.ManyToManyField(related_name='delibere', to='delibere.Amministrazione'),
        ),
    ]
