# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-09 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delibere', '0011_delibera_amministrazioni'),
    ]

    operations = [
        migrations.CreateModel(
            name='Normativa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrizione', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name_plural': 'amministrazioni',
            },
        ),
        migrations.AddField(
            model_name='delibera',
            name='normative',
            field=models.ManyToManyField(related_name='delibere', to='delibere.Normativa'),
        ),
    ]
