# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-09 18:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delibere', '0013_settore'),
    ]

    operations = [
        migrations.AddField(
            model_name='settore',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='delibere.Settore'),
        ),
    ]
