# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-09 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delibere', '0014_settore_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='settore',
            name='ss_id',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
