# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-10 07:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delibere', '0016_settore_sss_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='delibera',
            name='settori',
            field=models.ManyToManyField(related_name='delibere', to='delibere.Settore'),
        ),
    ]
