# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-01 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delibere', '0017_delibera_settori'),
    ]

    operations = [
        migrations.AddField(
            model_name='delibera',
            name='slug',
            field=models.CharField(help_text='Slug identificativo numer-data', max_length=14, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='delibera',
            name='codice',
            field=models.CharField(help_text='Codice identificativo anno/seduta.', max_length=7, null=True),
        ),
    ]
