# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-06 02:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delibere', '0021_auto_20170605_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delibera',
            name='slug',
            field=models.CharField(help_text='Slug identificativo numero-data', max_length=32, null=True, unique=True),
        ),
    ]
