# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-07 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delibere', '0022_auto_20170606_0246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delibera',
            name='numero',
            field=models.CharField(help_text="Numero della delibera, per quest'anno", max_length=16, verbose_name='Numero'),
        ),
    ]
