# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-13 09:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delibere', '0023_auto_20170607_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delibera',
            name='amministrazioni',
            field=models.ManyToManyField(null=True, related_name='delibere', to='delibere.Amministrazione'),
        ),
        migrations.AlterField(
            model_name='delibera',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data di creazione'),
        ),
        migrations.AlterField(
            model_name='delibera',
            name='gu_data_rettifica',
            field=models.DateField(blank=True, help_text='Data di pubblicazione della rettifica in Gazzetta Ufficiale', max_length=12, null=True, verbose_name='Pub. G.U. - Data rettifica'),
        ),
        migrations.AlterField(
            model_name='delibera',
            name='gu_numero_rettifica',
            field=models.CharField(blank=True, help_text='Numero di pubblicazione della rettifica in Gazzetta Ufficiale', max_length=12, null=True, verbose_name='Pub. G.U. - Numero rettifica'),
        ),
        migrations.AlterField(
            model_name='delibera',
            name='normative',
            field=models.ManyToManyField(null=True, related_name='delibere', to='delibere.Normativa'),
        ),
        migrations.AlterField(
            model_name='delibera',
            name='settori',
            field=models.ManyToManyField(null=True, related_name='delibere', to='delibere.Settore'),
        ),
        migrations.AlterField(
            model_name='delibera',
            name='slug',
            field=models.CharField(help_text='Slug identificativo numero-data', max_length=32, null=True, unique=True, verbose_name='Identificativo nella URL'),
        ),
        migrations.AlterField(
            model_name='delibera',
            name='tipo_delibera',
            field=models.CharField(blank=True, choices=[('Riparto/Assegnazioni', 'Riparto/Assegnazioni'), ('Direttive', 'Direttive'), ('Piani/Programmi', 'Piani/Programmi'), ('Altro', 'Altro')], max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='delibera',
            name='tipo_firmatario',
            field=models.CharField(blank=True, choices=[('Ministro', 'Ministro'), ('Altro', 'Altro')], max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='delibera',
            name='tipo_territorio',
            field=models.CharField(blank=True, choices=[('Regionale', 'Regionale'), ('Nazionale', 'Nazionale'), ('Multiregionale', 'Multiregionale'), ('Altro', 'Altro')], max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='delibera',
            name='updated_at',
            field=models.DateTimeField(null=True, verbose_name='Data di modifica'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='estensione',
            field=models.CharField(help_text="L'estensione del documento (doc, docx, pdf, ppt, xls, ...)", max_length=4),
        ),
        migrations.AlterField(
            model_name='documento',
            name='tipo_documento',
            field=models.CharField(choices=[('P', 'Principale'), ('A', 'Allegato')], max_length=1),
        ),
    ]
