# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-15 19:13
from __future__ import unicode_literals

from django.db import migrations


def set_publicata_to_true(apps, schema_editor):
    # We can't import the Delibere model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Delibera = apps.get_model('delibere', 'Delibera')
    for delibera in Delibera.objects.all():
        delibera.pubblicata = True
        delibera.save()


class Migration(migrations.Migration):

    dependencies = [
        ('delibere', '0025_auto_20170615_1753'),
    ]

    operations = [
        migrations.RunPython(set_publicata_to_true),
    ]
