# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-15 22:45
from __future__ import unicode_literals

from django.db import migrations
from delibere.models import Settore

# this migration rebuilds the tree object
# into the mptt representation, after migrating
# from a flat table

def rebuild_objects(apps, schema_editor):
    Settore.objects.rebuild()


class Migration(migrations.Migration):

    dependencies = [
        ('delibere', '0027_auto_20170615_2238'),
    ]

    operations = [
        migrations.RunPython(rebuild_objects),
    ]
