# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-16 00:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delibere', '0029_auto_20170616_0033'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amministrazione',
            options={'ordering': ('posizione',), 'verbose_name_plural': 'amministrazioni'},
        ),
        migrations.AddField(
            model_name='amministrazione',
            name='posizione',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
