# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-16 00:45
from __future__ import unicode_literals

from django.db import migrations

def add_posizione_to_amministrazione(apps, schema_editor):
    # We can't import the Amministrazione model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Amministrazione = apps.get_model('delibere', 'Amministrazione')
    order = 0
    for obj in Amministrazione.objects.all():
        order += 1
        obj.posizione = order
        obj.save()

class Migration(migrations.Migration):

    dependencies = [
        ('delibere', '0030_auto_20170616_0040'),
    ]

    operations = [
        migrations.RunPython(add_posizione_to_amministrazione),
    ]
