# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-16 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delibere', '0032_auto_20170616_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delibera',
            name='gu_tipologia',
            field=models.CharField(blank=True, choices=[('O', 'Ordinaria'), ('S', 'Supplemento'), ('I', 'Inserzioni?')], help_text='Tipo di pubblicazione in Gazzetta Ufficiale', max_length=12, null=True, verbose_name='Pub. G.U. - Tipologia'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='estensione',
            field=models.CharField(blank=True, help_text="L'estensione del documento (doc, docx, pdf, ppt, xls, ...)", max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='documento',
            name='nome',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
