# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-21 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delibere', '0033_auto_20170616_0743'),
    ]

    operations = [
        migrations.AddField(
            model_name='delibera',
            name='numero_ord',
            field=models.CharField(blank=True, help_text="Numero della delibera, adatto per l'ordinamento", max_length=16, null=True, verbose_name='Numero'),
        ),
    ]
