# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-21 16:21
from __future__ import unicode_literals

import string

from django.db import migrations

def update_numero_ord_field(apps, schema_editor):
    # We can't import the Delibere model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Delibera = apps.get_model('delibere', 'Delibera')
    for delibera in Delibera.objects.all():
        num = delibera.numero
        delibera.numero_ord =  "{0:04d}".format(
            int(num.rstrip(string.punctuation).rstrip(string.letters))
        ) + num.lstrip(string.digits)
        delibera.save()



class Migration(migrations.Migration):

    dependencies = [
        ('delibere', '0034_delibera_numero_ord'),
    ]

    operations = [
        migrations.RunPython(update_numero_ord_field),
    ]
