# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-09-22 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delibere', '0035_auto_20170621_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delibera',
            name='codice',
            field=models.CharField(default=None, help_text='Codice identificativo anno/seduta.', max_length=8, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='documento',
            name='nome',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
    ]
