# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-02 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delibere', '0036_auto_20170922_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='visibilita_allegati',
            field=models.BooleanField(default=True, help_text='Marcare la casella per rendere un allegato non visibile', verbose_name='Visibilit\xe0 allegato'),
        ),
    ]
