# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-03 09:35
from __future__ import unicode_literals

import delibere.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delibere', '0037_documento_visibilita_allegati'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='file',
            field=models.FileField(max_length=255, upload_to=delibere.models.upload_to),
        ),
    ]
